### ISSUE TITLE
Add parameters to data boxes of current panels

### ISSUE THREAD

**Issue by RiboRings** [RiboRings/iSEEtree#25]
Most of the data boxes of the current panels are still empty. Meaningful data parameters should be discussed and added.

The main difference between data box and visualisation box is that data boxes should contain parameters that significantly change the data in a plot (number of points, values of the axes, measured metric, transformations, etc.), whereas visualisation parameters just change aesthetics (shape by, colour by, etc.).

**Comment by ElySeraidarian** [comment]
Hey, I am currently trying to add some data parameters however I'm not sure which one could be added (and not considered a visual one) so here is a quick list I made.
 
AbundancePlot : 
- assay.type (however I already tried this and it basically doesn't change anything on the plot)
- order_sample_by
- decreasing

AbundanceDensityPlot : 
- flipped
- shape_by
- order_descending?

RowTreePlot : 
- order_tree
- node_size_by/edge_size_by/tip_size_by ? Feels more like visual parameters ?

It feels like a lot could be also visual parameters so I want to be sure which to add

**Comment by RiboRings** [comment]
AbundancePlot:
- maybe if you set `use_relative = FALSE`, then the assay.type will modify the plot. But probably it is preferable to visualise all kinds of assays with the heatmap panel instead of the abundance plot one. Instead of assay.type, how about adding a checkbox for the use_relative argument? (data box)
- order_sample_by + decreasing sounds like a good idea (data box)

AbundanceDensityPlot
- the iSEE panels tend to be long and thin (at least in my tiny screen), so flipping the axes would probably make this plot hard to see. But feel free to test it, maybe I'm wrong (data box)
- shape_by is a visual param, but it's definitely a good idea. The docs say it's disabled for `layout = "density"`, so you could play and try to hide shape_by based on layout value (visual box)
- order_descending sounds good. If it's tricky to give TRUE, FALSE and NA as options, you can check how it was done for add.ellipse in RDAPlot (data box)

RowTreePlot
- order_tree sounds good (data box)
- node_size_by/edge_size_by/tip_size_by, yes they are visual params. It would be nice to add them, but then the visual box becomes too long. As a solution, the reducedDimPlot panel has a checkbox at the beginning of the visual box that opens up only the selected aesthetics. Feel free to try that out if you have time.

**Comment by RiboRings** [comment]
Some other possible ideas for the RDAPlot:
- confidence.level
- add.significance
- add.expl.var
- visual params for ellipse, vectors and arrows, which might need a checkbox solution as mentioned above for RowTreePlot

**Comment by antagomir** [comment]
Would be good to coordinate with mia/miaVIz: if some of these options could/should be made available there, then just called here, that might be preferable?

**Comment by ElySeraidarian** [comment]
These are already existing parameters in miaViz functions, we are just creating ways to change these parameters in our visualization plot.

**Comment by RiboRings** [comment]
Completed with https://github.com/microbiome/iSEEtree/pull/28
