### ISSUE TITLE
Error in get: object '.SigLength'

### ISSUE THREAD

**Issue by danique-mulder** [RiboRings/iSEEtree#31]
Listening on http://127.0.0.1:6564
Warning in .refineParameters(extra[[idx]], se) :
  no 'reducedDims' with non-zero dimensions for 'ReducedDimensionPlot'
Warning: Error in get: object '.SigLength' not found
  48: get
  47: .findNextFromTable
  46: addNextMethod
  44: callNextMethod
  43: .createObservers
  41: .initialize_server
  40: server
   3: runApp
   2: print.shiny.appobj
   1: <Anonymous>

**Comment by RiboRings** [comment]
Mh the error `Warning: Error in get: object '.SigLength' not found` is unrelated to reducedDim. If you are able to provide a reproducible example I might find how to fix that.

**Comment by RiboRings** [comment]
Fixed with https://github.com/microbiome/iSEEtree/pull/32
